### ISSUE TITLE
possible fork?

### ISSUE THREAD

**Issue by ghost** [RomaniukVadim/backup-my-github#3]
Does this repo has any relation to https://github.com/ghaiklor/backup-my-github ?

**Comment by ghaiklor** [comment]
it has, the source code was copied as is from my repository
must to say, that it is inappropriate action - copying source code without mentioning the original author

**Comment by RomaniukVadim** [comment]
Absolutely and 100% fork, yes. But, LICENSE https://github.com/ghaiklor/backup-my-github/blob/master/LICENSE allow this. See rule №0.

**Comment by ghaiklor** [comment]
yep, that's what I said here - https://github.com/ghaiklor/backup-my-github/issues/1

of course, in our GitHub community, it's common to make forks, not just copy the source code. So, in that way, this action is inappropriate. Though, I made this script for fun in half an hour and that is why I choose this license. Make sure, that copyleft is still there (in your repository), everything else is fine.

**Comment by ghost** [comment]
Got you, thanks for the clarification!
